try {
    throw 'Houve um erro'
} catch {
    console.log('At√© aqui')
}